### ISSUE TITLE
RSA Cipher too large if other client than 8.6 (10.98 for example)

### ISSUE THREAD

**Issue by IntinteDAO** [OpenCoreMMO/OpenCoreMMO#480]
**Describe the bug**
Server may crash if authentication is done with another Tibia client (10.98)

**To Reproduce**
1. Set Tibia 10.98 on OTClient
2. Try to authorize
3. Crash

**Expected behavior**
Error / Information about not supported version etc.
Display: "Client version not supported"

**Desktop (please complete the following information):**
 - OS: Linux
 - Client OTClient
 - Version 10.98

Unhandled exception. Org.BouncyCastle.Crypto.DataLengthException: input too large for RSA cipher.
   at Org.BouncyCastle.Crypto.Engines.RsaCoreEngine.ConvertInput(Byte[] inBuf, Int32 inOff, Int32 inLen)
   at Org.BouncyCastle.Crypto.Engines.RsaEngine.ProcessBlock(Byte[] inBuf, Int32 inOff, Int32 inLen)
   at NeoServer.Server.Security.Rsa.Decrypt(Byte[] data) in /home/fervi/Intinte/LibreTibia/Jenkinson8.6/OpenCoreMMO/src/ApplicationServer/NeoServer.Server.Security/RSA.cs:line 17
   at NeoServer.Networking.Packets.Incoming.AccountLoginPacket..ctor(IReadOnlyNetworkMessage message) in /home/fervi/Intinte/LibreTibia/Jenkinson8.6/OpenCoreMMO/src/NetworkingServer/NeoServer.Networking.Packets/Incoming/AccountLoginPacket.cs:line 23
   at NeoServer.Networking.Handlers.LogIn.AccountLoginHandler.HandleMessage(IReadOnlyNetworkMessage message, IConnection connection) in /home/fervi/Intinte/LibreTibia/Jenkinson8.6/OpenCoreMMO/src/NetworkingServer/NeoServer.Networking.Handlers/LogIn/AccountLoginHandler.cs:line 22
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by MarcusSilvaDev** [comment]
@IntinteDAO  thank you for report. 


![image](https://user-images.githubusercontent.com/17841549/228289381-c65d92f3-27cf-437e-af98-4acfeedb2101.png)
![image](https://user-images.githubusercontent.com/17841549/228289432-27305665-bdc7-426c-ae19-eb7f93f60b78.png)
